---
# Ansible Inventory für Network Traffic Logger
all:
  children:
    monitoring_servers:
      hosts:
        netlogger:
          ansible_host: localhost
          ansible_connection: local
      vars:
        ansible_user: admin
        ansible_become: yes
        ansible_become_method: sudo
